# Generated by Django 2.2.1 on 2019-08-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.CharField(max_length=500)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
